export { default as IconBirdClass } from "./icon-bird-class"
export { default as IconBoatClass } from "./icon-boat-class"
export { default as IconBox } from "./icon-box"
export { default as IconDolphinClass } from "./icon-dolphin-class"
export { default as IconEgg } from "./icon-egg"
export { default as IconHorseClass } from "./icon-horse-class"
export { default as IconHoverClass } from "./icon-hover-class"
export { default as IconJetClass } from "./icon-jet-class"
export { default as IconRocketClass } from "./icon-rocket-class"
export { default as IconSubmarineClass } from "./icon-submarine-class"
export { IconX } from "./icon-x"
